### ISSUE TITLE
Could not find walker with name: ReadCountWalker

### ISSUE THREAD

**Issue by vladsavelyev** [crukci-bioinformatics/gatk-tools#2]
Hi Matt,

Sorry for coming back with an issue again. It's likely me doing something wrong - I'm not very familiar with GATK. I'm getting an error when running run-gatk after building:

```
./gatk-tools-1.0-SNAPSHOT/bin/run-gatk -T ReadCountWalker
```
Giving me:
```
##### ERROR MESSAGE: Invalid command line: Malformed walker argument: Could not find walker with name: ReadCountWalker
```

I followed the installation steps, including installing the GATK jar file using maven, and setting the `CLASSPATH_PREFIX` variable (without it set correctly, it gives another kind of error, so I think I didn't screw this up). However both the manually built version `gatk-tools-1.0-SNAPSHOT` and downloaded release `gatk-tools-0.2.2` are giving same error about the missing ReadCountWalker. Can you suggest please?

Vlad

**Comment by eldrid01** [comment]
Hi Vlad,

It looks like the maven-generated run-gatk script is causing some issues for you of a sort I've not seen before. An alternative way of running the tools would be to set the classpath explicitly and run the CommandLineGATK class as follows:

java -classpath GenomeAnalysisTK.jar:gatk-tools-1.0-SNAPSHOT/lib/commons-math3-3.6.1.jar:gatk-tools-1.0-SNAPSHOT/lib/gatk-tools-1.0-SNAPSHOT.jar org.broadinstitute.gatk.engine.CommandLineGATK -T ReadCountWalker

Depending on which directory you run the command from you might need to replace each of the jar files in the colon-separated classpath with full paths.

Matt

**Comment by vladsavelyev** [comment]
Thanks Matt,

Still same error though, unfortunately.

**Comment by vladsavelyev** [comment]
Actually it's only MacOS giving an error. I just tried on Linux - and it worked!

**Comment by eldrid01** [comment]
This is very odd. I'm also using both Mac OS X and Linux but am drawing a blank on what might be causing the difference for you.

The error message you are seeing is the result of the ReadCountWalker class not being present on the Java classpath. It should be contained within gatk-tools-0.2.2.jar, or gatk-tools-1.0-SNAPSHOT.jar for the version you built, which can be found in the lib directory. You can check by listing the contents of the jar file using 'jar tf'.

**Comment by vladsavelyev** [comment]
It seems to be in the jar files:

[~/git/gatk-tools]$ jar tf ./target/gatk-tools/lib/gatk-tools-1.0-SNAPSHOT.jar                                                                                                                                                     *[master]
```
META-INF/
META-INF/MANIFEST.MF
org/
org/cruk/
org/cruk/gatk/
org/cruk/gatk/walkers/
org/cruk/gatk/walkers/ReadCountWalker.class
org/cruk/gatk/walkers/CalculateSNVMetrics.class
org/cruk/gatk/walkers/ReadCountWalker$OverlappingReadPairPileupMode.class
org/cruk/gatk/walkers/CalculateSNVMetrics$BasePileupElementFilter.class
org/cruk/gatk/walkers/CalculateSNVMetrics$OverlappingReadPairPileupMode.class
org/cruk/gatk/walkers/ReadCountWalker$Variant.class
org/cruk/gatk/walkers/CalculateSNVMetrics$1.class
META-INF/maven/
META-INF/maven/org.cruk.gatk/
META-INF/maven/org.cruk.gatk/gatk-tools/
META-INF/maven/org.cruk.gatk/gatk-tools/pom.xml
META-INF/maven/org.cruk.gatk/gatk-tools/pom.properties
```

[~/git/gatk-tools]$ jar tf ./gatk-tools-0.2.2/lib/gatk-tools-0.2.2.jar   
```                                                                                                                                                         *[master]
META-INF/
META-INF/MANIFEST.MF
org/
org/cruk/
org/cruk/gatk/
org/cruk/gatk/walkers/
org/cruk/gatk/walkers/CalculateSNVMetrics$1.class
org/cruk/gatk/walkers/CalculateSNVMetrics$BasePileupElementFilter.class
org/cruk/gatk/walkers/CalculateSNVMetrics$OverlappingReadPairPileupMode.class
org/cruk/gatk/walkers/CalculateSNVMetrics.class
org/cruk/gatk/walkers/ReadCountWalker$OverlappingReadPairPileupMode.class
org/cruk/gatk/walkers/ReadCountWalker$Variant.class
org/cruk/gatk/walkers/ReadCountWalker.class
META-INF/maven/
META-INF/maven/org.cruk.gatk/
META-INF/maven/org.cruk.gatk/gatk-tools/
META-INF/maven/org.cruk.gatk/gatk-tools/pom.xml
META-INF/maven/org.cruk.gatk/gatk-tools/pom.properties
```

**Comment by eldrid01** [comment]
Yes, the contents of the jar files are as expected. I don't really understand why the ReadCountWalker is not being found by the GATK runtime when run on your Mac. Can you tell me which version of GATK you're using and which version of the Java runtime (using java -version)?
Thanks, Matt

**Comment by eldrid01** [comment]
Not sure if this was ever resolved but I can't reproduce the problem which seems to be very specific/local to vladsaveliev.

**Comment by vladsavelyev** [comment]
Ah, I forgot about this issue. Sorry for not getting back to you with java version - I must have missed the notification about the reply... Can't remember if I managed to find a workaround. Hope it just got resolved on its own :)
