### ISSUE TITLE
CalculateSNVMetrics issue with variant count

### ISSUE THREAD

**Issue by CraigJAnderson** [crukci-bioinformatics/gatk-tools#3]
Hi,

I'm using Strelka2 to genotype normal:tumour and am interested in low frequency variants, using CalculateSNVMetrics as part of a pipeline to remove SNVs with fewer than 4X on the tumour ALT. As such, the measure VariantAlleleCount is pretty interesting, though I don't see how it's 4 in each instance. Could you give me more insight into how it's calculated please?

Thanks.

##look at 1:125142813_C/A
(Normal on left, tumour on right)
1       125142813       .       C       A       .       PASS    DP=109;Depth=109;DepthControl=66;DistanceToAlignmentEnd=41.00;DistanceToAlignmentEndMAD=11.50;DistanceToAlignmentEndMedian=42.00;HomopolymerLength=2;LowMapQual=0.00;MMQSDiff=34.63;MMQSDiffMedian=41.00;MQ=60;MQ0=0;MapQualDiff=0.00;MapQualDiffMedian=0.00;NT=ref;QSS=36;QSS_NT=36;ReadCount=108;ReadCountControl=66;ReadPosRankSum=-0.05;ReferenceStrandBias=0.439;Repeat=4;SGT=CC->AC;SNVSB=0;SOMATIC;SomaticEVS=7.45;StrandBias=0.454;TQSS=1;TQSS_NT=1;VariantAlleleCount=4;VariantAlleleCountControl=1;VariantAlleleFrequency=0.037;VariantAlleleFrequencyControl=0.015;VariantBaseQual=32.75;VariantBaseQualMedian=39.00;VariantMMQS=45.75;VariantMMQSMedian=41.00;VariantMapQual=60.00;VariantMapQualMedian=60.00;VariantStrandBias=0.500                                                                                                                                                                     DP:FDP:SDP:SUBDP:AU:CU:GU:TU     65:1:0:0:1,1:63,65:0,0:0,0      43:0:0:0:3,3:40,40:0,0:0,0

##looked at another site: 10:96037571_A/T
10      96037571        .       A       T       .       PASS    DP=90;Depth=90;DepthControl=49;DistanceToAlignmentEnd=48.50;DistanceToAlignmentEndMAD=8.00;DistanceToAlignmentEndMedian=45.50;HomopolymerLength=4;LowMapQual=0.00;MMQSDiff=12.57;MMQSDiffMedian=4.00;MQ=60;MQ0=0;MapQualDiff=0.00;MapQualDiffMedian=0.00;NT=ref;QSS=38;QSS_NT=38;ReadCount=87;ReadCountControl=47;ReadPosRankSum=0.51;ReferenceStrandBias=0.362;Repeat=4;SGT=AA->AT;SNVSB=0;SOMATIC;SomaticEVS=8.96;StrandBias=0.379;TQSS=1;TQSS_NT=1;VariantAlleleCount=4;VariantAlleleCountControl=1;VariantAlleleFrequency=0.046;VariantAlleleFrequencyControl=0.021;VariantBaseQual=32.75;VariantBaseQualMedian=39.00;VariantMMQS=19.50;VariantMMQSMedian=4.00;VariantMapQual=60.00;VariantMapQualMedian=60.00;VariantStrandBias=0.250                                                                                                                                                                            DP:FDP:SDP:SUBDP:AU:CU:GU:TU     49:1:0:0:48,48:0,0:0,0:0,1      40:2:0:0:35,37:0,1:0,0:3,3

**Comment by eldrid01** [comment]
Hi Craig,

These metrics are calculated using the alignments in the normal and tumour BAM files that you presumably generated with an aligner such as BWA-MEM. The tool uses the GATK and is implemented as a LocusWalker subclass that essentially 'walks' across all loci that are covered by reads in the BAM file(s); it then uses the in-built pileup functionality that GATK provides to get counts of reads with different alleles at each locus.

Strelka is one of a number of variant callers that realign reads in the vicinity of loci where it thinks there may be a mutation. It does this by performing a local assembly of those reads. This means that what Strelka sees when it calls variants and what it reports, e.g. in its AU, CU, GU, TU fields, is not necessarily what you see if you view your BAM file in a genome browser such as IGV.

The number you get for the VariantAlleleCount metric should be what you see in IGV subject to whatever minimum mapping and base quality thresholds you specified when running CalculateSNVMetrics. Those thresholds can also account for differences between what the variant caller reports and what you get running CalculateSNVMetrics. Note that Strelka has 2 tiers of reads when it computes support for a variant, one with more stringent settings for the mapping and base quality scores.

In both the examples you gave, I assume you are concerned about the difference between the number of supporting reads of 4 given in VariantAlleleCount and 3 reads reported by Strelka. I suggest loading the BAM files for both tumour and normal into IGV and inspecting the reads covering these loci.

Strelka used to output the alignments for the reads it realigned as BAM files by default but I think that was no longer the case in the more recent version I ran some months back. It might still be possible to configure Strelka to output the realigned BAMs if you really want to get to the bottom of this for these two variants.

Hope that helps,
Matt

**Comment by CraigJAnderson** [comment]
Sorry for the slow reply and thanks for your quick one.

Your response is somewhat as I expected, but good to establish for sure- without going into all the gory detail, I'm interested in what is making it through our pipeline and why so that I can dig into the LowEVS Strelka calls. I'm happy with my expectations of CalculateSNVMetrics and will use it appropriately. Cheers!
